# Generated by Django 5.0.3 on 2024-04-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_recipeingredient_options_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
